development:
  adapter: postgresql
  encoding: unicode
  database: dinner_dash_development
  pool: 5
  username: RbyWoo 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: dinner_dash_test
  pool: 5
  username: RbyWoo
  password: 
